Remove unused region_name in port_dump()
What actually signaled this to me was the warning:

mv88e6xxx_dump.c: In function ‘port_dump’:
mv88e6xxx_dump.c:593:30: warning: too many arguments for format [-Wformat-extra-args]
  593 |         sprintf(region_name, "port", port);
      |                              ^~~~~~

Since nothing is actually done with the region_name string, delete it.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>